version: '3'
services:      
  app:
    image: urlshortner-server
    build: .
    ports:
     - "8090:8090"
    container_name: app
    environment:
      - NODE_ENV=production
    links: 
      - postgres:postgres
    depends_on: 
      - postgres

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=tillhub
      - POSTGRES_PASSWORD=T1llhu8
      - POSTGRES_DB=urlshortner
    volumes:
      - ~/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"